//! # aurora-core
//!
//! Aurora's mobile-relevant analysis methods in Rust — ONE numerical source
//! of truth, compiled everywhere (iOS via Swift FFI, Android via
//! Kotlin/uniffi, desktop as a native lib).
//!
//! **The trust gate:** every method here is parity-tested against the Python
//! Aurora engine on a golden corpus (`golden/golden.json`, generated by
//! `golden/gen_golden.py` from the real engine). Change-point indices must
//! match EXACTLY; statistics match to 1e-9 relative. If a port drifts from
//! the reference, the tests fail — a subtly-wrong port would silently
//! destroy the product's whole premise ("the math is real"), so this suite
//! is the most important artifact in the crate.
//!
//! Methods (Milestone 1 — the Counsel-critical subset):
//! - PELT change-point detection (rbf + l2 costs) — the "break line"
//! - Welch's t-test (exact p) — "is the break bigger than normal swings?"
//! - AR(1) forecast with residual bands — the honest range
//!
//! Next milestones: HMM regimes, robust-z/MAD anomalies, uniffi bindings.

mod ar1;
mod pelt;
mod stats;

pub use ar1::{ar1_forecast, Ar1Forecast};
pub use pelt::{detect_changepoints, CostModel};
pub use stats::{betainc_reg, ln_gamma, norm_ppf, welch_t, WelchResult};
