//! Golden-parity suite: Rust aurora-core vs the Python Aurora engine.
//!
//! golden.json is generated by golden/gen_golden.py running the REAL Python
//! engine (ruptures PELT, scipy Welch, Aurora AR1). These tests are the
//! product's trust gate: exact change-point equality, 1e-9 statistics.

use serde::Deserialize;
use std::path::Path;

#[derive(Deserialize)]
struct Golden {
    changepoint: Vec<CpCase>,
    welch: Vec<WelchCase>,
    ar1: Vec<Ar1Case>,
}

#[derive(Deserialize)]
struct CpCase {
    name: String,
    values: Vec<f64>,
    model: String,
    penalty: f64,
    expected_indices: Vec<usize>,
}

#[derive(Deserialize)]
struct WelchCase {
    name: String,
    a: Vec<f64>,
    b: Vec<f64>,
    expected_t: f64,
    expected_p: f64,
}

#[derive(Deserialize)]
struct Ar1Case {
    name: String,
    values: Vec<f64>,
    horizon: usize,
    alpha: f64,
    expected_a: f64,
    expected_b: f64,
    expected_forecast: Vec<f64>,
    expected_resid_std: f64,
    mc_lo: Vec<f64>,
    mc_hi: Vec<f64>,
}

fn golden() -> Golden {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("golden/golden.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("golden.json missing at {path:?} ({e}) — run golden/gen_golden.py"));
    serde_json::from_str(&raw).expect("golden.json parse")
}

fn rel_close(a: f64, b: f64, tol: f64) -> bool {
    let scale = a.abs().max(b.abs()).max(1e-300);
    (a - b).abs() / scale <= tol || (a - b).abs() <= 1e-12
}

#[test]
fn changepoint_parity_exact() {
    let g = golden();
    let mut failures = Vec::new();
    for c in &g.changepoint {
        let model = aurora_core::CostModel::parse(&c.model).unwrap();
        let got = aurora_core::detect_changepoints(&c.values, model, c.penalty);
        if got != c.expected_indices {
            failures.push(format!(
                "{}: expected {:?}, got {:?}",
                c.name, c.expected_indices, got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "change-point parity failures ({} of {}):\n{}",
        failures.len(),
        g.changepoint.len(),
        failures.join("\n")
    );
}

#[test]
fn welch_parity_1e9() {
    let g = golden();
    for c in &g.welch {
        let r = aurora_core::welch_t(&c.a, &c.b);
        assert!(
            rel_close(r.t, c.expected_t, 1e-9),
            "{}: t {} vs {}",
            c.name,
            r.t,
            c.expected_t
        );
        assert!(
            rel_close(r.p, c.expected_p, 1e-9),
            "{}: p {} vs {}",
            c.name,
            r.p,
            c.expected_p
        );
    }
}

#[test]
fn ar1_parity() {
    let g = golden();
    for c in &g.ar1 {
        let f = aurora_core::ar1_forecast(&c.values, c.horizon, c.alpha)
            .unwrap_or_else(|| panic!("{}: too few points", c.name));
        assert!(rel_close(f.a, c.expected_a, 1e-9), "{}: a {} vs {}", c.name, f.a, c.expected_a);
        assert!(rel_close(f.b, c.expected_b, 1e-9), "{}: b {} vs {}", c.name, f.b, c.expected_b);
        assert!(
            rel_close(f.resid_std, c.expected_resid_std, 1e-9),
            "{}: resid_std {} vs {}",
            c.name,
            f.resid_std,
            c.expected_resid_std
        );
        for (i, (got, want)) in f.forecast.iter().zip(&c.expected_forecast).enumerate() {
            assert!(
                rel_close(*got, *want, 1e-9),
                "{}: forecast[{}] {} vs {}",
                c.name,
                i,
                got,
                want
            );
        }
        // Bands: Python is an 800-draw MC around N(fc, resid_std); Rust is the
        // analytic quantile the MC estimates. The MC's own standard error at
        // the 2.5/97.5 percentiles is ≈0.095σ per point (√(p(1−p)/800)/φ(z)),
        // and we compare ~240 points, so the worst draw sits near 3 SE.
        // Bound: 0.35σ — wide enough for the MC's noise, tight enough that a
        // wrong quantile (e.g. 90% vs 95%) still fails loudly (Δ≈0.31σ… caught
        // by the many points that sit well past it).
        let tol = 0.35 * f.resid_std.max(1e-12);
        for i in 0..f.forecast.len() {
            assert!(
                (f.lo[i] - c.mc_lo[i]).abs() <= tol,
                "{}: lo[{}] {} vs MC {} (tol {})",
                c.name,
                i,
                f.lo[i],
                c.mc_lo[i],
                tol
            );
            assert!(
                (f.hi[i] - c.mc_hi[i]).abs() <= tol,
                "{}: hi[{}] {} vs MC {} (tol {})",
                c.name,
                i,
                f.hi[i],
                c.mc_hi[i],
                tol
            );
        }
    }
}
